name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 코드를 체크아웃하는 단계

      - name: Set up GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # 배포할 브랜치 설정 (gh-pages)
          folder: .  # 루트 디렉토리부터 배포 (원하는 디렉토리로 설정 가능)
          token: ${{ secrets.GITHUB_TOKEN }}
